name: Windows-Build

permissions:
  contents: write

on:
  workflow_dispatch: # This triggers the workflow manually
    inputs:
      link_commits:
        description: 'Links to all commits since the last release'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # ... rest of your steps ...

      - name: Get Commit Links
        id: get_commit_links
        run: |
          echo "::set-output name=COMMIT_LINKS::$(git log --format='%s (%h)' $(git describe --tags --abbrev=0 HEAD^)..HEAD | sed 's/ /%20/g' | awk '{print "* [%s](https://github.com/$GITHUB_REPOSITORY/commit/"$2")"}')"
        shell: bash

      - name: Publish
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.exe
          name: Galaxy Widgets v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body: |
            > [!NOTE]
            > This release was manually triggered.
            >
            > **Commits since the last release:**
            > ${{ steps.get_commit_links.outputs.COMMIT_LINKS }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
