name: Electron Build and Release

on:
  push:
    branches:
      - main # You can change this to your main branch name

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Windows with --asar
        run: npm run build:windows

      - name: Zip Output Folder
        run: |
          tar -caf oneui-widgets.zip oneui-desktop-widgets-win32-x64
        working-directory: ${{ github.workspace }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: Release
          release_name: Release Stable
          body: Automatic Build
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload ZIP Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: oneui-widgets
          path: oneui-widgets.zip

      - name: Attach Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: oneui-widgets.zip
          asset_name: oneui-widgets.zip
          asset_content_type: application/zip
