name: Electron Build and Upload

on:
  push:
    branches:
      - main # You can change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App for Windows with --asar
        run: npm run build:windows

      - name: Zip Output Folder
        run: |
          cd oneui-desktop-widgets-win32-x64
          zip -r oneui-widgets.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v2
        with:
          name: oneui-widgets
          path: oneui-desktop-widgets-win32-x64/oneui-widgets.zip

